### ISSUE TITLE
Enable Github Pages to host the demo pages live

### ISSUE THREAD

**Issue by davelab6** [jenskutilek/homecomputer-fonts#1]
The demo page links in README aren't live web pages which is a little disappointing XD

If you enable GH pages in https://github.com/jenskutilek/homecomputer-fonts/settings then they can be :)

**Comment by felipesanches** [comment]
thanks, Dave!

**Comment by felipesanches** [comment]
I enabled gh-pages on my fork: https://felipesanches.github.io/homecomputer-fonts/

It renders the index.md and the link to the c64 demo page works, but not the benchmark one. I was not able to figure out why, though.

**Comment by jenskutilek** [comment]
GH pages have been enabled since forever, is it just me or are they impossible to discover from the repo? (and vice versa, how to get to the repo from the GH pages other than hacking the URL?): https://jenskutilek.github.io/homecomputer-fonts/

**Comment by jenskutilek** [comment]
Ah, I haven't looked at this in a while ... the README.md isn't used for the GH pages, so I updated the links in README to point to the live GH pages.

**Comment by jenskutilek** [comment]
> I enabled gh-pages on my fork: https://felipesanches.github.io/homecomputer-fonts/
> 
> It renders the index.md and the link to the c64 demo page works, but not the workbench one. I was not able to figure out why, though.

Both pages work for me. I tested in Safari.
