### ISSUE TITLE
vf vs static fonts (usable not only on the web with css)

### ISSUE THREAD

**Issue by alexmyczko** [jenskutilek/homecomputer-fonts#10]
i'm trying to create debian packages of your fonts, and also using vfit:
https://github.com/jonpalmisc/vfit/issues/9

but i'm not able to get results more like:
https://github.com/rewtnull/amigafonts

maybe there's a simple trick i'm blind to see?

**Comment by alexmyczko** [comment]
it looks much better in a terminal, than in the preview... sorry for the noise!

**Comment by jenskutilek** [comment]
No problem! As the fonts are based on an 8 pixel grid, they look best at that size or multiples of 8.

Thank you for taking the effort to build a Debian package :)
