### ISSUE TITLE
Workbench: `b` sidebearings are off (lsb is zero?)

### ISSUE THREAD

**Issue by davelab6** [jenskutilek/homecomputer-fonts#11]
`HbHdHpHqHhH`

<img width="616" alt="Screenshot 2023-06-20 at 13 49 45" src="https://github.com/jenskutilek/homecomputer-fonts/assets/261579/5a44a019-7f56-4c96-a6d9-92cfc4711351">

Taken from latest ttf in https://github.com/jenskutilek/homecomputer-fonts/tree/master/Workbench/fonts/variable

**Comment by jenskutilek** [comment]
Hm, I can't reproduce ... which version of FontGoggles are you using?

![Bildschirmfoto 2023-06-22 um 09 11 33](https://github.com/jenskutilek/homecomputer-fonts/assets/3185950/63339585-614c-4f91-97db-e103abd6785d)

**Comment by davelab6** [comment]
I can no longer reproduce with latest repo fonts + latest fontgoggles (Version 1.7.3) so closing =) Sorry for noise
