### ISSUE TITLE
Quadratic only?

### ISSUE THREAD

**Issue by davelab6** [jenskutilek/homecomputer-fonts#13]
https://github.com/jenskutilek/homecomputer-fonts/tree/master/documentation/Design%20process says

> In the production source files, those curves are cubic Bézier curves (PostScript curves), because the build process with fontmake will try to remove overlaps for static font export, and this is only supported for cubic curves.
> 
> So the curves are automatically converted from PostScript to TrueType in the final fonts, which makes them a tiny bit less optimized than the hand-drawn curves here.

But fontmake has a `--keep-overlaps` arg to not remove any overlap :)

**Comment by jenskutilek** [comment]
I set the option to keep overlaps in config.yaml
