### ISSUE TITLE
GF Glyph coverage

### ISSUE THREAD

**Issue by vv-monsalve** [jenskutilek/homecomputer-fonts#15]
Fontbakery Fail reported regarding Glyph coverage. The fonts covers overall `GF_Latin_Kernel` instead of `GF_Latin_Core`, so it doesn't have e.g. combining marks. 

**Sixtyfour** - 129 missing glyps reported
**Workbench** - 131 missing glyphs reported

We will need confirmation about this from @davelab6. 

<details><summary>🔥 <b>FAIL:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>

>
>Google Fonts expects that fonts in its collection support at least the minimal set of characters defined in the `GF-latin-core` glyph-set.
>
* 🔥 **FAIL** Missing required codepoints:

	- 0x0308 (COMBINING DIAERESIS)

	- 0x0300 (COMBINING GRAVE ACCENT)

	- 0x0301 (COMBINING ACUTE ACCENT)

	- 0x030B (COMBINING DOUBLE ACUTE ACCENT)

	- 0x0304 (COMBINING MACRON)

	- 0x0102 (LATIN CAPITAL LETTER A WITH BREVE)

	- 0x0100 (LATIN CAPITAL LETTER A WITH MACRON)

	- 0x0104 (LATIN CAPITAL LETTER A WITH OGONEK)

	- 0x0106 (LATIN CAPITAL LETTER C WITH ACUTE)

	- 0x010C (LATIN CAPITAL LETTER C WITH CARON)

	- 0x010A (LATIN CAPITAL LETTER C WITH DOT ABOVE)

	- 0x010E (LATIN CAPITAL LETTER D WITH CARON)

	- 0x0110 (LATIN CAPITAL LETTER D WITH STROKE)

	- 0x011A (LATIN CAPITAL LETTER E WITH CARON)

	- 0x0116 (LATIN CAPITAL LETTER E WITH DOT ABOVE)

	- 0x0112 (LATIN CAPITAL LETTER E WITH MACRON)

	- 0x0118 (LATIN CAPITAL LETTER E WITH OGONEK)

	- 0x011E (LATIN CAPITAL LETTER G WITH BREVE)

	- 0x0122 (LATIN CAPITAL LETTER G WITH CEDILLA)

	- 0x0120 (LATIN CAPITAL LETTER G WITH DOT ABOVE)

	- 0x0126 (LATIN CAPITAL LETTER H WITH STROKE)

	- 0x0132 (LATIN CAPITAL LIGATURE IJ)

	- 0x0130 (LATIN CAPITAL LETTER I WITH DOT ABOVE)

	- 0x012A (LATIN CAPITAL LETTER I WITH MACRON)

	- 0x012E (LATIN CAPITAL LETTER I WITH OGONEK)

	- 0x0136 (LATIN CAPITAL LETTER K WITH CEDILLA)

	- 0x0139 (LATIN CAPITAL LETTER L WITH ACUTE)

	- 0x013D (LATIN CAPITAL LETTER L WITH CARON)

	- 0x013B (LATIN CAPITAL LETTER L WITH CEDILLA)

	- 0x0141 (LATIN CAPITAL LETTER L WITH STROKE)

	- 0x0143 (LATIN CAPITAL LETTER N WITH ACUTE)

	- 0x0147 (LATIN CAPITAL LETTER N WITH CARON)

	- 0x0145 (LATIN CAPITAL LETTER N WITH CEDILLA)

	- 0x014A (LATIN CAPITAL LETTER ENG)

	- 0x0150 (LATIN CAPITAL LETTER O WITH DOUBLE ACUTE)

	- 0x014C (LATIN CAPITAL LETTER O WITH MACRON)

	- 0x0154 (LATIN CAPITAL LETTER R WITH ACUTE)

	- 0x0158 (LATIN CAPITAL LETTER R WITH CARON)

	- 0x0156 (LATIN CAPITAL LETTER R WITH CEDILLA)

	- 0x015A (LATIN CAPITAL LETTER S WITH ACUTE)

	- 0x0160 (LATIN CAPITAL LETTER S WITH CARON)

	- 0x015E (LATIN CAPITAL LETTER S WITH CEDILLA)

	- 0x0218 (LATIN CAPITAL LETTER S WITH COMMA BELOW)

	- 0x1E9E (LATIN CAPITAL LETTER SHARP S)

	- 0x0164 (LATIN CAPITAL LETTER T WITH CARON)

	- 0x021A (LATIN CAPITAL LETTER T WITH COMMA BELOW)

	- 0x016C (LATIN CAPITAL LETTER U WITH BREVE)

	- 0x0170 (LATIN CAPITAL LETTER U WITH DOUBLE ACUTE)

	- 0x016A (LATIN CAPITAL LETTER U WITH MACRON)

	- 0x0172 (LATIN CAPITAL LETTER U WITH OGONEK)

	- 0x016E (LATIN CAPITAL LETTER U WITH RING ABOVE)

	- 0x1E82 (LATIN CAPITAL LETTER W WITH ACUTE)

	- 0x0174 (LATIN CAPITAL LETTER W WITH CIRCUMFLEX)

	- 0x1E84 (LATIN CAPITAL LETTER W WITH DIAERESIS)

	- 0x1E80 (LATIN CAPITAL LETTER W WITH GRAVE)

	- 0x0176 (LATIN CAPITAL LETTER Y WITH CIRCUMFLEX)

	- 0x0178 (LATIN CAPITAL LETTER Y WITH DIAERESIS)

	- 0x1EF2 (LATIN CAPITAL LETTER Y WITH GRAVE)

	- 0x0179 (LATIN CAPITAL LETTER Z WITH ACUTE)

	- 0x017D (LATIN CAPITAL LETTER Z WITH CARON)

	- 0x017B (LATIN CAPITAL LETTER Z WITH DOT ABOVE)

	- 0x0103 (LATIN SMALL LETTER A WITH BREVE)

	- 0x0101 (LATIN SMALL LETTER A WITH MACRON)

	- 0x0105 (LATIN SMALL LETTER A WITH OGONEK)

	- 0x0107 (LATIN SMALL LETTER C WITH ACUTE)

	- 0x010D (LATIN SMALL LETTER C WITH CARON)

	- 0x010B (LATIN SMALL LETTER C WITH DOT ABOVE)

	- 0x010F (LATIN SMALL LETTER D WITH CARON)

	- 0x0111 (LATIN SMALL LETTER D WITH STROKE)

	- 0x011B (LATIN SMALL LETTER E WITH CARON)

	- 0x0117 (LATIN SMALL LETTER E WITH DOT ABOVE)

	- 0x0113 (LATIN SMALL LETTER E WITH MACRON)

	- 0x0119 (LATIN SMALL LETTER E WITH OGONEK)

	- 0x011F (LATIN SMALL LETTER G WITH BREVE)

	- 0x0123 (LATIN SMALL LETTER G WITH CEDILLA)

	- 0x0121 (LATIN SMALL LETTER G WITH DOT ABOVE)

	- 0x0127 (LATIN SMALL LETTER H WITH STROKE)

	- 0x0133 (LATIN SMALL LIGATURE IJ)

	- 0x012B (LATIN SMALL LETTER I WITH MACRON)

	- 0x012F (LATIN SMALL LETTER I WITH OGONEK)

	- 0x0237 (LATIN SMALL LETTER DOTLESS J)

	- 0x0137 (LATIN SMALL LETTER K WITH CEDILLA)

	- 0x013A (LATIN SMALL LETTER L WITH ACUTE)

	- 0x013E (LATIN SMALL LETTER L WITH CARON)

	- 0x013C (LATIN SMALL LETTER L WITH CEDILLA)

	- 0x0142 (LATIN SMALL LETTER L WITH STROKE)

	- 0x0144 (LATIN SMALL LETTER N WITH ACUTE)

	- 0x0148 (LATIN SMALL LETTER N WITH CARON)

	- 0x0146 (LATIN SMALL LETTER N WITH CEDILLA)

	- 0x014B (LATIN SMALL LETTER ENG)

	- 0x0151 (LATIN SMALL LETTER O WITH DOUBLE ACUTE)

	- 0x014D (LATIN SMALL LETTER O WITH MACRON)

	- 0x0155 (LATIN SMALL LETTER R WITH ACUTE)

	- 0x0159 (LATIN SMALL LETTER R WITH CARON)

	- 0x0157 (LATIN SMALL LETTER R WITH CEDILLA)

	- 0x015B (LATIN SMALL LETTER S WITH ACUTE)

	- 0x0161 (LATIN SMALL LETTER S WITH CARON)

	- 0x015F (LATIN SMALL LETTER S WITH CEDILLA)

	- 0x0219 (LATIN SMALL LETTER S WITH COMMA BELOW)

	- 0x0165 (LATIN SMALL LETTER T WITH CARON)

	- 0x021B (LATIN SMALL LETTER T WITH COMMA BELOW)

	- 0x016D (LATIN SMALL LETTER U WITH BREVE)

	- 0x0171 (LATIN SMALL LETTER U WITH DOUBLE ACUTE)

	- 0x016B (LATIN SMALL LETTER U WITH MACRON)

	- 0x0173 (LATIN SMALL LETTER U WITH OGONEK)

	- 0x016F (LATIN SMALL LETTER U WITH RING ABOVE)

	- 0x1E83 (LATIN SMALL LETTER W WITH ACUTE)

	- 0x0175 (LATIN SMALL LETTER W WITH CIRCUMFLEX)

	- 0x1E85 (LATIN SMALL LETTER W WITH DIAERESIS)

	- 0x1E81 (LATIN SMALL LETTER W WITH GRAVE)

	- 0x0177 (LATIN SMALL LETTER Y WITH CIRCUMFLEX)

	- 0x1EF3 (LATIN SMALL LETTER Y WITH GRAVE)

	- 0x017A (LATIN SMALL LETTER Z WITH ACUTE)

	- 0x017E (LATIN SMALL LETTER Z WITH CARON)

	- 0x017C (LATIN SMALL LETTER Z WITH DOT ABOVE)

	- 0x0307 (COMBINING DOT ABOVE)

	- 0x0302 (COMBINING CIRCUMFLEX ACCENT)

	- 0x030C (COMBINING CARON)

	- 0x0306 (COMBINING BREVE)

	- 0x030A (COMBINING RING ABOVE)

	- 0x0303 (COMBINING TILDE)

	- 0x0312 (COMBINING TURNED COMMA ABOVE)

	- 0x0326 (COMBINING COMMA BELOW)

	- 0x0327 (COMBINING CEDILLA)

	- 0x0328 (COMBINING OGONEK)

	- 0x02DD (DOUBLE ACUTE ACCENT)

	- 0x02C7 (CARON)

	- 0x02D8 (BREVE)
 

	- 0x02DB (OGONEK)
 [code: missing-codepoints]
</div></details>

**Comment by davelab6** [comment]
That's fine with me, these are historically related fonts and the originals weren't extensive

**Comment by vv-monsalve** [comment]
@davelab6 In that case, should we enforce our [vertical metrics](https://github.com/jenskutilek/homecomputer-fonts/issues/7#issuecomment-1650658135) policy (leaving open the option for the font to be updated with more language support? Or, due to the historical reasons, would we make an exception also in this regard?

**Comment by vv-monsalve** [comment]
It was [accepted](https://github.com/jenskutilek/homecomputer-fonts/issues/7#issuecomment-1688962423) to publish the font with a reduced Glyphset.
