### ISSUE TITLE
Use custom VF axes for CRT bleed and scanlines

### ISSUE THREAD

**Issue by felipesanches** [jenskutilek/homecomputer-fonts#2]
it is very cool that you've got variation axes for CRT bleed and scanlines. I just disagree to the use of wdth and wght for those variations

**Comment by jenskutilek** [comment]
I agree. Any reservations against using custom axes regarding the prospective release on Google Fonts, @davelab6?

**Comment by RosaWagner** [comment]
The problem with the custom axes is that they need to be registered, and the process is quite long and the font can be pending for weeks/month. I would advise to build a case in this issue: https://github.com/google/fonts/issues/3425 with images so all.

**Comment by jenskutilek** [comment]
First I thought you meant the axes need to go through the OpenType specification axis registration process and was prepared to give up ;) But now I see Google has its own registry.

I changed the axis names in the fonts and added proposals for the new axes to be included in the Google Fonts Axis Registry: https://github.com/google/fonts/issues/3697, https://github.com/google/fonts/issues/3699
