### ISSUE TITLE
Minute and Second glyphs

### ISSUE THREAD

**Issue by vv-monsalve** [jenskutilek/homecomputer-fonts#20]
Despite `minute U+2032` and `second U+2033` glyphs are not included in the glyphset, it would be a good addition to the fonts given their concept. What would you say?

<img width="515" alt="Screen Shot 2023-09-04 at 20 26 03" src="https://github.com/jenskutilek/homecomputer-fonts/assets/48698976/09fe46c4-56ed-4824-86f2-af73974ad319">

**Comment by jenskutilek** [comment]
Good idea, I've added them.
