### ISSUE TITLE
Fix STAT table

### ISSUE THREAD

**Issue by RosaWagner** [jenskutilek/homecomputer-fonts#3]

**Comment by RosaWagner** [comment]
Sorry hit enter after writing the title…

To match GF specs:
- Fallback names for ITAL axis is Roman/Italic (and not regular)
- Roman should be linked with ital `linkedValue: 1`
- Custom axis shouldn't have a fallback named "Regular", they should have specific ones, or at worse "normal". Check out axis registry (https://github.com/google/fonts/tree/main/axisregistry) for some inspiration
- Custom axes should have at least some range, so 2 values, 0 -> 100, with 0 as elided default name and 100 -> non elided name which can even take the axis name. Same, check out axis registry for some inspiration.

--> Please propose axis name and fallback name/position in this issue so we can register the custom axes (otherwise we can't ship the font) https://github.com/google/fonts/issues/3425

**Comment by jenskutilek** [comment]
I've updated the STAT tables to reflect the latest axis registry proposals (https://github.com/googlefonts/axisregistry/issues/17, https://github.com/googlefonts/axisregistry/issues/18)

I've omitted the italic axis from the STAT tables. For an 8 pixel tall font, it is unlikely that there ever would be an italic.
