### ISSUE TITLE
FAIL: Check that legacy accents aren't used in composite glyphs.

### ISSUE THREAD

**Issue by vv-monsalve** [jenskutilek/homecomputer-fonts#30]
@jenskutilek This fail is reported under he latest version of FB. 

<details><summary>🔥 <b>FAIL:</b> Check that legacy accents aren't used in composite glyphs. (derived from com.google.fonts/check/legacy_accents) (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/legacy_accents">com.google.fonts/check/legacy_accents</a>)</summary><div>

>
>Legacy accents should not be used in accented glyphs. The use of legacy accents in accented glyphs breaks the mark to mark combining feature that allows a font to stack diacritics over one glyph. Use combining marks instead as a component in composite glyphs.
>
>Legacy accents should not have anchors and positive width (at least as wide as their bounding box). They are often used independently of a letter, either as a placeholder for an expected combined mark+letter combination in MacOS, or separately. For instance, U+00B4 (ACUTE ACCENT) is often mistakenly used as an apostrophe, U+0060 (GRAVE ACCENT) is used in Markdown to notify code blocks, and ^ is used as an exponential operator in maths.
>
* 🔥 **FAIL** Legacy accent "tilde" are too narrow. [code: legacy-accents-width]
</div></details>

**Comment by vv-monsalve** [comment]
We discussed about this fail today and it was accepted we can ignore this for this font given it has Latin Kernell support. So I'm closing this here.
@jenskutilek I think we're ready to go in that case. I'll move ahead with the onboarding process and let you know if anything else is needed.

**Comment by jenskutilek** [comment]
Thanks!

**Comment by vv-monsalve** [comment]
@jenskutilek I've sent you an email regarding the designer's bio info that is also required. Please let me know if you received it.

**Comment by jenskutilek** [comment]
@vv-monsalve I received it and submitted the bio a couple of days ago.

**Comment by vv-monsalve** [comment]
Excellent. I'll start the biography addition and let you know if something else is needed.
