### ISSUE TITLE
Repo structure and License file

### ISSUE THREAD

**Issue by RosaWagner** [jenskutilek/homecomputer-fonts#5]
OFL.txt is incorrect, should be something like `Copyright 2021 The Font Name Project Authors (github URL)`

I do think that to handle in the best way the QA and onboarding process, you should separate the 2 families in 2 repo with their own license each. It will allow to clean up the repo and make it clearer for external users.

**Comment by jenskutilek** [comment]
I was pondering whether it was better to make one family from the two families because they are very similar in concept. Having two separate families is maybe too much attention for those closely related styles. What do you think @RosaWagner?

**Comment by RosaWagner** [comment]
As you think it's best. In that case we would need 2 distinct directories to separate sources and binaries — cause on GF side, we onboard 2 distinct families
 You can keep the same license at root:
"Copyright 2021 The home Computer Fonts Project Authors (github URL)"
--> which need to be copy pasted in copyright string of the fonts

**Comment by jenskutilek** [comment]
I split the Workbench family into its own repo: https://github.com/jenskutilek/homecomputer-fonts-wb
