### ISSUE TITLE
Onboarding step 1: make a version of the font without custom axis

### ISSUE THREAD

**Issue by RosaWagner** [jenskutilek/homecomputer-fonts#8]
Since registering the custom axis will take a while I suggest to first onboard the default style without any custom axis.
Then we'll just have to update the two families with an added axis.

**Comment by davelab6** [comment]
@jenskutilek I think this was a good idea ~2 years ago but now can be closed as the axis registration process (led by @vv-monsalve) is (finally) close at hand :)

**Comment by vv-monsalve** [comment]
I left a note in the Add Font issue opened for these fonts. This issue can be closed here.
